base_url = "https://ben-tannheimer.ch"
title = "Benjamin Tannheimer"
description = "Personal blog"

default_language = "en"
generate_feed = true
minify_html = true

[markdown]
  highlight_code = true
  highlight_theme = "visual-studio-dark"
  external_links_target_blank = true
  external_links_no_follow = true
  external_links_no_referrer = true
  smart_punctuation = true

[extra]
  d3_nav = [
    { name = "HOME", path = "/" },
    { name = "POSTS", path = "/posts/" },
    { name = "PROJECTS", path = "/projects" },   
    # { name = "CONFIG", path = "/config/" },
  ]
  d3_icon = "/icon.png"
  # d3_twitter = "therealFIGBERT"
  d3_author = "Benjamin Tannheimer"
